'use client'

import { useState } from 'react'
import { Sparkles } from 'lucide-react'
import CategoryMover from '@/components/CategoryMover'
import ThreadSummary from '@/components/ThreadSummary'
import type { EmailCategory } from '@/types'

type State = 'OPEN' | 'SNOOZED' | 'CLOSED'
type Analysis = { summary: string; riskLevel: string; nextAction: string | null; provider: string } | null

const STATES: { value: State; label: string }[] = [
  { value: 'OPEN', label: 'Open' },
  { value: 'SNOOZED', label: 'Snoozed' },
  { value: 'CLOSED', label: 'Closed' },
]

// Relationship framing for the per-thread AI read (no "risk" jargon).
const HEALTH: Record<string, { label: string; color: string }> = {
  LOW:      { label: 'Healthy',    color: 'var(--cold)' },
  MEDIUM:   { label: 'Watch',      color: 'var(--attention)' },
  HIGH:     { label: 'At risk',    color: 'var(--hot)' },
  CRITICAL: { label: 'Going cold', color: 'var(--hot)' },
}

/**
 * The thread context rail: a single AI surface (relationship health + summary +
 * next action + an inline "Catch me up" expander), plus the two thread controls
 * a solo user needs — status (open/snoozed/closed) and category. AI analysis
 * arrives as serializable props from the server page.
 */
export default function ThreadContextRail({
  conversationId,
  initialState,
  category,
  analysis,
}: {
  conversationId: string
  initialState: State
  category: EmailCategory
  analysis: Analysis
}) {
  const [state, setState] = useState<State>(initialState)
  const [busy, setBusy] = useState(false)

  const health = analysis ? (HEALTH[analysis.riskLevel] ?? HEALTH.LOW) : null

  async function changeState(next: State) {
    setState(next); setBusy(true)
    try {
      await fetch(`/api/conversations/${conversationId}/state`, {
        method: 'POST', headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ state: next }),
      })
    } finally { setBusy(false) }
  }

  return (
    <div className="rail">
      {/* AI insight — the single AI surface */}
      <section className="rail-section">
        <div className="rail-ai-head">
          <span className="rail-ai-icon"><Sparkles size={13} /></span>
          <span className="rail-ai-title">AI insight</span>
          {health && (
            <span className="rail-risk" style={{ color: health.color }}>
              <span className="rail-risk-dot" style={{ background: health.color }} />
              {health.label}
            </span>
          )}
        </div>
        {analysis ? (
          <>
            <p className="rail-ai-summary">{analysis.summary}</p>
            {analysis.nextAction && <p className="rail-ai-action">→ {analysis.nextAction}</p>}
            {analysis.provider === 'local' && (
              <span className="rail-offline" title="Generated by the offline heuristic — add a Gemini key for full AI analysis">
                offline mode
              </span>
            )}
            <ThreadSummary conversationId={conversationId} />
          </>
        ) : (
          <p className="rail-empty">Not analyzed yet. Insight appears after the next sync/analysis.</p>
        )}
      </section>

      {/* Properties */}
      <section className="rail-section">
        <h3 className="rail-label">Properties</h3>

        <div className="rail-prop">
          <span className="rail-prop-k">Status</span>
          <div className="rail-seg" role="group" aria-label="Conversation state">
            {STATES.map((s) => (
              <button
                key={s.value}
                type="button"
                onClick={() => changeState(s.value)}
                disabled={busy}
                data-active={state === s.value}
                className="rail-seg-btn"
              >
                {s.label}
              </button>
            ))}
          </div>
        </div>

        <div className="rail-prop">
          <span className="rail-prop-k">Category</span>
          <div className="rail-prop-v"><CategoryMover conversationId={conversationId} current={category} /></div>
        </div>
      </section>
    </div>
  )
}
