import { Fragment } from 'react'
import { notFound } from 'next/navigation'
import Link from 'next/link'
import { ArrowLeft, Sparkles } from 'lucide-react'
import { requireOrgPage } from '@/lib/org'
import { prisma } from '@/lib/prisma'
import PriorityBadge from '@/components/ui/PriorityBadge'
import MessageCard from '@/components/inbox/MessageCard'
import Composer from '@/components/Composer'
import CategoryMover from '@/components/CategoryMover'
import ThreadCollab from '@/components/ThreadCollab'
import ThreadSummary from '@/components/ThreadSummary'
import { getReadyDraft } from '@/services/draft.service'
import { dayLabel } from '@/lib/format-time'
import type { EmailCategory, PriorityLevel } from '@/types'

const RISK: Record<string, { label: string; color: string; bg: string; border: string }> = {
  LOW:      { label: 'Low risk',    color: 'var(--cold)',      bg: 'var(--cold-dim)',      border: 'var(--cold-border)'      },
  MEDIUM:   { label: 'Medium risk', color: 'var(--attention)', bg: 'var(--attention-dim)', border: 'var(--attention-border)' },
  HIGH:     { label: 'High risk',   color: 'var(--hot)',       bg: 'var(--hot-dim)',        border: 'var(--hot-border)'       },
  CRITICAL: { label: 'Critical',    color: 'var(--hot)',       bg: 'var(--hot-dim)',        border: 'var(--hot-border)'       },
}

function initials(name: string): string {
  return name.split(' ').map(w => w[0]?.toUpperCase() ?? '').slice(0, 2).join('') || '?'
}

export default async function ConversationPage({
  params,
  searchParams,
}: {
  params: Promise<{ id: string }>
  searchParams: Promise<{ draft?: string }>
}) {
  const { id } = await params
  const { draft: draftParam } = await searchParams

  const ctx = await requireOrgPage()

  // findFirst (not findUnique) so we can scope by org + active integration —
  // prevents reading another org's conversation, and hides chats from
  // disconnected channels.
  const conv = await prisma.conversation.findFirst({
    where: { id, organizationId: ctx.organization.id, integration: { isActive: true } },
    include: {
      contact: true,
      messages: { orderBy: { sentAt: 'asc' } },
      analysis: true,
    },
  })

  if (!conv) notFound()

  const analysis = conv.analysis
  const r = analysis ? (RISK[analysis.riskLevel] ?? RISK.LOW) : null
  // 'local' = heuristic fallback ran instead of the full AI model — label it.
  const analyzedBy = ((analysis?.analysisData as { provider?: string } | null)?.provider) ?? 'gemini'
  const channelName = conv.channel === 'GMAIL' ? 'Gmail' : 'Telegram'
  const now = new Date()

  // Pending auto-draft to pre-fill, and the one-click "?draft=1" intent.
  const readyDraft = await getReadyDraft(ctx.organization.id, conv.id)
  const wantsAutoDraft = draftParam === '1'

  // Pre-compute grouping: day separators + "continuation" rows (same sender,
  // <10 min apart) that render tighter against the previous card.
  const rows = conv.messages.map((msg, i) => {
    const prev = conv.messages[i - 1]
    const sentAt = new Date(msg.sentAt)
    const newDay = !prev || new Date(prev.sentAt).toDateString() !== sentAt.toDateString()
    const cont =
      !newDay &&
      prev !== undefined &&
      prev.direction === msg.direction &&
      sentAt.getTime() - new Date(prev.sentAt).getTime() < 10 * 60_000
    return { msg, sentAt, newDay, cont }
  })

  return (
    <div className="chat">
      {/* Header */}
      <div className="chat-header">
        <Link href="/inbox" className="thread-back">
          <ArrowLeft size={15} /> Inbox
        </Link>

        <div className="chat-head-row">
          <div className="chat-avatar">{initials(conv.contact.name)}</div>
          <div style={{ minWidth: 0, flex: 1 }}>
            <h2 className="chat-name">{conv.contact.name}</h2>
            <div className="chat-sub">
              <span className="chat-chip">{channelName}</span>
              {conv.contact.email && <span className="chat-email">{conv.contact.email}</span>}
            </div>
            {conv.subject && <p className="chat-subject">{conv.subject}</p>}
          </div>
          <div style={{ display: 'flex', alignItems: 'center', gap: 8, flexShrink: 0 }}>
            <CategoryMover conversationId={conv.id} current={conv.category as EmailCategory} />
            <PriorityBadge level={conv.priority as PriorityLevel} />
          </div>
        </div>

        {analysis && r && (
          <div className="chat-ai" style={{ background: r.bg, borderColor: r.border }}>
            <div className="chat-ai-head">
              <Sparkles size={13} style={{ color: r.color }} />
              <span style={{ color: r.color }}>
                {analyzedBy === 'local' ? 'Quick scan' : 'AI insight'} · {r.label}
              </span>
              {analyzedBy === 'local' && (
                <span
                  title="Generated by the offline heuristic — full AI analysis will replace it on the next run"
                  style={{ fontSize: 10.5, fontWeight: 600, color: 'var(--text-muted)', marginLeft: 6 }}
                >
                  offline mode
                </span>
              )}
            </div>
            <p className="chat-ai-summary">{analysis.summary}</p>
            {analysis.nextAction && (
              <p className="chat-ai-action">→ {analysis.nextAction}</p>
            )}
          </div>
        )}

        <ThreadCollab
          conversationId={conv.id}
          initialAssigneeId={conv.assigneeId}
          initialState={conv.state as 'OPEN' | 'SNOOZED' | 'CLOSED'}
        />

        {conv.messages.length > 6 && <ThreadSummary conversationId={conv.id} />}
      </div>

      {/* Messages */}
      <div className="chat-messages thread-messages">
        {rows.length === 0 ? (
          <div className="inbox-empty" style={{ padding: '60px 24px' }}>
            <p style={{ margin: 0, fontSize: 14, fontWeight: 600, color: 'var(--text-primary)' }}>No messages yet</p>
            <p style={{ margin: 0, fontSize: 13, color: 'var(--text-muted)' }}>
              New messages in this thread will appear here after the next sync.
            </p>
          </div>
        ) : (
          rows.map(({ msg, sentAt, newDay, cont }) => (
            <Fragment key={msg.id}>
              {newDay && (
                <div className="chat-day-sep">
                  <span>{dayLabel(sentAt, now)}</span>
                </div>
              )}
              <MessageCard msg={msg} contactName={conv.contact.name} now={now} cont={cont} />
            </Fragment>
          ))
        )}
      </div>

      {/* Reply composer — Gmail only for now */}
      {conv.channel === 'GMAIL' && conv.contact.email && (
        <Composer
          conversationId={conv.id}
          initialDraft={readyDraft}
          autoDraft={wantsAutoDraft && !readyDraft}
        />
      )}
    </div>
  )
}
