'use client'

/**
 * Onboarding step 2 — the AI business interview. The user describes their
 * business, the generator proposes a full workspace (industry, objects,
 * pipelines, KPIs, copilot), they PREVIEW it and only then apply
 * (propose → confirm → execute; nothing is materialized before "Use this
 * workspace"). Offline/no-key mode degrades to a labelled template.
 */
import { useState } from 'react'
import { ArrowRight, RefreshCw, Sparkles, Wand2 } from 'lucide-react'
import type { WorkspaceBlueprint } from '@/lib/workspace/blueprint'
import { iconFor } from '@/lib/workspace/icons'
import { announceWorkspaceUpdated } from '@/lib/workspace/use-workspace-schema'

interface Generated {
  blueprint: WorkspaceBlueprint
  provider: 'gemini' | 'local'
  templateKey: string
}

interface TemplateOption {
  key: string
  label: string
  objects: string[]
}

const inputStyle: React.CSSProperties = {
  width: '100%',
  padding: '10px 11px',
  fontSize: 13.5,
  borderRadius: 9,
  border: '1px solid var(--border)',
  background: 'var(--bg-base)',
  color: 'var(--text-primary)',
  outline: 'none',
}

export default function WorkspaceSetupStep({ onDone }: { onDone: () => void }) {
  const [description, setDescription] = useState('')
  const [services, setServices] = useState('')
  const [channels, setChannels] = useState('')
  const [busy, setBusy] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [generated, setGenerated] = useState<Generated | null>(null)

  const [templates, setTemplates] = useState<TemplateOption[] | null>(null)
  const [showTemplates, setShowTemplates] = useState(false)

  async function generate(templateKey?: string) {
    if (!templateKey && description.trim().length < 8) {
      setError('A sentence or two about the business helps the AI get it right')
      return
    }
    setBusy(true)
    setError(null)
    try {
      const r = await fetch('/api/workspace/generate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(
          templateKey
            ? { templateKey }
            : { answers: { description: description.trim(), services: services.trim() || undefined, channels: channels.trim() || undefined } },
        ),
      })
      const d = await r.json().catch(() => null)
      if (!r.ok) {
        setError(d?.error ?? 'Could not generate the workspace')
        return
      }
      setGenerated(d as Generated)
    } catch {
      setError('Network error — try again')
    } finally {
      setBusy(false)
    }
  }

  async function apply() {
    if (!generated) return
    setBusy(true)
    setError(null)
    try {
      const r = await fetch('/api/workspace/apply', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          blueprint: generated.blueprint,
          provider: generated.provider,
          answers: description.trim().length >= 8 ? { description: description.trim(), services: services.trim() || undefined, channels: channels.trim() || undefined } : undefined,
        }),
      })
      if (!r.ok) {
        const d = await r.json().catch(() => null)
        setError(d?.error ?? 'Could not apply the workspace')
        return
      }
      announceWorkspaceUpdated()
      onDone()
    } catch {
      setError('Network error — try again')
    } finally {
      setBusy(false)
    }
  }

  async function openTemplates() {
    setShowTemplates(true)
    if (templates) return
    try {
      const r = await fetch('/api/workspace/templates')
      const d = await r.json().catch(() => null)
      setTemplates((d?.templates as TemplateOption[]) ?? [])
    } catch {
      setTemplates([])
    }
  }

  // ── Preview state ──────────────────────────────────────────────────────────
  if (generated) {
    const bp = generated.blueprint
    return (
      <div>
        <div style={{ display: 'flex', alignItems: 'center', gap: 9, marginBottom: 6 }}>
          <Sparkles size={17} style={{ color: 'var(--accent)' }} />
          <h2 style={{ margin: 0, fontSize: 17, fontWeight: 700, color: 'var(--text-primary)' }}>
            Your {bp.profile.industryLabel.toLowerCase()} workspace
          </h2>
        </div>
        <p style={{ margin: '0 0 14px', fontSize: 12.5, color: 'var(--text-muted)' }}>
          {generated.provider === 'gemini'
            ? 'Generated by AI from your description — review before applying.'
            : 'Built from our closest industry template (offline mode) — review before applying.'}
        </p>

        <div style={{ display: 'flex', flexWrap: 'wrap', gap: 6, marginBottom: 14 }}>
          {bp.objects.map((o) => {
            const Icon = iconFor(o.icon)
            return (
              <span
                key={o.key}
                style={{ display: 'inline-flex', alignItems: 'center', gap: 6, fontSize: 12.5, fontWeight: 600, color: 'var(--text-secondary)', border: '1px solid var(--border)', borderRadius: 8, padding: '5px 10px', background: 'var(--bg-base)' }}
              >
                <Icon size={13} />
                {o.plural}
                {o.pipeline?.length ? <span style={{ fontWeight: 400, color: 'var(--text-muted)' }}>· {o.pipeline.length} stages</span> : null}
              </span>
            )
          })}
        </div>

        <div style={{ fontSize: 12.5, color: 'var(--text-secondary)', lineHeight: 1.7, marginBottom: 16 }}>
          <div><strong style={{ color: 'var(--text-primary)' }}>Copilot:</strong> {bp.copilot.title}</div>
          {bp.dashboard.length > 0 && (
            <div><strong style={{ color: 'var(--text-primary)' }}>Dashboard:</strong> {bp.dashboard.map((w) => w.label ?? w.objectKey).join(' · ')}</div>
          )}
          {bp.automationIdeas.length > 0 && (
            <div><strong style={{ color: 'var(--text-primary)' }}>Automation ideas:</strong> {bp.automationIdeas.slice(0, 3).join(' · ')}</div>
          )}
        </div>

        {error && <p style={{ margin: '0 0 12px', fontSize: 12.5, color: 'var(--hot)' }}>{error}</p>}

        <button type="button" onClick={apply} disabled={busy} className="btn-primary" style={{ width: '100%', justifyContent: 'center', gap: 8, marginBottom: 8 }}>
          {busy ? 'Applying…' : 'Use this workspace'} {!busy && <ArrowRight size={15} />}
        </button>
        <div style={{ display: 'flex', gap: 8 }}>
          <button type="button" className="btn-ghost" disabled={busy} onClick={() => setGenerated(null)} style={{ flex: 1, justifyContent: 'center', fontSize: 13 }}>
            <RefreshCw size={13} /> Adjust & regenerate
          </button>
          <button type="button" className="btn-ghost" disabled={busy} onClick={onDone} style={{ flex: 1, justifyContent: 'center', fontSize: 13, color: 'var(--text-muted)' }}>
            Skip for now
          </button>
        </div>
      </div>
    )
  }

  // ── Interview state ────────────────────────────────────────────────────────
  return (
    <div>
      <div style={{ display: 'flex', alignItems: 'center', gap: 9, marginBottom: 6 }}>
        <Wand2 size={17} style={{ color: 'var(--accent)' }} />
        <h2 style={{ margin: 0, fontSize: 17, fontWeight: 700, color: 'var(--text-primary)' }}>What does your company do?</h2>
      </div>
      <p style={{ margin: '0 0 14px', fontSize: 13, color: 'var(--text-secondary)', lineHeight: 1.55 }}>
        Velnox shapes itself around your business — a dental clinic gets Patients and Treatment plans, an agency gets Projects and Campaigns.
      </p>

      <textarea
        autoFocus
        rows={3}
        value={description}
        onChange={(e) => setDescription(e.target.value)}
        placeholder="e.g. We run a dental clinic — cleanings, braces and implants for families."
        style={{ ...inputStyle, resize: 'vertical', fontFamily: 'inherit', marginBottom: 10 }}
      />
      <input
        value={services}
        onChange={(e) => setServices(e.target.value)}
        placeholder="Main services (optional)"
        style={{ ...inputStyle, marginBottom: 10 }}
      />
      <input
        value={channels}
        onChange={(e) => setChannels(e.target.value)}
        placeholder="How do customers usually reach you? (optional)"
        style={{ ...inputStyle, marginBottom: error ? 8 : 14 }}
      />
      {error && <p style={{ margin: '0 0 12px', fontSize: 12.5, color: 'var(--hot)' }}>{error}</p>}

      <button type="button" onClick={() => void generate()} disabled={busy} className="btn-primary" style={{ width: '100%', justifyContent: 'center', gap: 8, marginBottom: 8 }}>
        {busy ? 'Designing your workspace…' : 'Generate my workspace'} {!busy && <Sparkles size={15} />}
      </button>

      {!showTemplates ? (
        <button type="button" className="btn-ghost" onClick={openTemplates} style={{ width: '100%', justifyContent: 'center', fontSize: 13 }}>
          Or start from a template
        </button>
      ) : (
        <div style={{ display: 'flex', flexDirection: 'column', gap: 6, marginTop: 4 }}>
          {(templates ?? []).map((t) => (
            <button
              key={t.key}
              type="button"
              disabled={busy}
              onClick={() => void generate(t.key)}
              className="btn-ghost"
              style={{ justifyContent: 'flex-start', textAlign: 'left', fontSize: 13, display: 'flex', gap: 8 }}
            >
              <strong style={{ fontWeight: 600 }}>{t.label}</strong>
              <span style={{ color: 'var(--text-muted)', fontSize: 12, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>
                {t.objects.join(', ')}
              </span>
            </button>
          ))}
          {templates === null && <span style={{ fontSize: 12.5, color: 'var(--text-muted)', textAlign: 'center' }}>Loading templates…</span>}
        </div>
      )}

      <button type="button" onClick={onDone} style={{ display: 'block', margin: '12px auto 0', border: 'none', background: 'none', fontSize: 12.5, color: 'var(--text-muted)', cursor: 'pointer' }}>
        Skip — set up later
      </button>
    </div>
  )
}
