'use client'

import { useState } from 'react'
import { AlertCircle, ChevronDown, ChevronUp, Loader, Sparkles } from 'lucide-react'
import type { ThreadSummary as ThreadSummaryData } from '@/types'

type Loaded = ThreadSummaryData & { provider: string }

/**
 * "Catch me up" — on-demand structured summary of a long thread. Generates on
 * first click (cached server-side), then toggles open/closed. Degrades to a
 * labelled offline summary when no AI key is configured.
 */
export default function ThreadSummary({ conversationId }: { conversationId: string }) {
  const [open, setOpen] = useState(false)
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [data, setData] = useState<Loaded | null>(null)

  async function load() {
    if (data) {
      setOpen((o) => !o)
      return
    }
    if (loading) return
    setLoading(true)
    setError(null)
    try {
      const res = await fetch(`/api/conversations/${conversationId}/summarize`, { method: 'POST' })
      const d = await res.json().catch(() => ({}))
      if (!res.ok) throw new Error(d.error ?? 'Failed to summarize')
      setData(d as Loaded)
      setOpen(true)
    } catch (e) {
      setError(e instanceof Error ? e.message : 'Failed to summarize')
    } finally {
      setLoading(false)
    }
  }

  return (
    <div className="rail-summary">
      <button
        type="button"
        className="rail-summary-btn"
        onClick={() => void load()}
        disabled={loading}
        aria-expanded={open}
      >
        {loading ? <Loader size={13} style={{ animation: 'spin 1s linear infinite' }} /> : <Sparkles size={13} />}
        Catch me up
        {data && (open ? <ChevronUp size={13} /> : <ChevronDown size={13} />)}
      </button>

      {error && (
        <p className="rail-summary-error" role="alert">
          <AlertCircle size={12} style={{ flexShrink: 0 }} />
          {error}
        </p>
      )}

      {open && data && (
        <div className="rail-summary-card">
          <p className="ts-tldr">{data.tldr}</p>

          {data.keyPoints.length > 0 && (
            <ul className="ts-list">
              {data.keyPoints.map((p, i) => (
                <li key={i}>{p}</li>
              ))}
            </ul>
          )}

          {data.openItems.length > 0 && (
            <>
              <p className="ts-label">Open items</p>
              <ul className="ts-list ts-open">
                {data.openItems.map((p, i) => (
                  <li key={i}>{p}</li>
                ))}
              </ul>
            </>
          )}

          {data.provider === 'local' && (
            <span className="ts-offline" title="Generated by the offline heuristic — add a Gemini key for full AI summaries">
              offline summary
            </span>
          )}
        </div>
      )}
    </div>
  )
}
